# Generated by Django 2.2.6 on 2019-10-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ins_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pass_ratio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_line', models.CharField(max_length=20, verbose_name='产品线')),
                ('apply_dt', models.CharField(max_length=20, verbose_name='申请日期')),
                ('ins_score', models.CharField(max_length=20, verbose_name='ins分数')),
                ('type_name', models.CharField(max_length=20, verbose_name='类别,如:省份')),
                ('type_value', models.CharField(max_length=20, verbose_name='类别值,如:云南省')),
                ('loan_nums', models.IntegerField(verbose_name='进件量')),
                ('pass_ratio', models.FloatField(verbose_name='通过率')),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-createDateTime',),
            },
        ),
        migrations.DeleteModel(
            name='ins_score',
        ),
    ]
