# Generated by Django 2.2.6 on 2019-10-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ins_app1', '0002_auto_20191011_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_ratio',
            name='pass_ratio',
            field=models.FloatField(null=True, verbose_name='通过率'),
        ),
    ]
