# Generated by Django 2.2.6 on 2019-11-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ins_app1', '0005_fpd_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpd_ratio',
            name='apply_mth',
            field=models.CharField(max_length=20, verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='fpd_ratio',
            name='fpd_ratio',
            field=models.FloatField(null=True, verbose_name='率'),
        ),
        migrations.AlterField(
            model_name='fpd_ratio',
            name='ins_score',
            field=models.CharField(max_length=20, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='fpd_ratio',
            name='prod_line',
            field=models.CharField(max_length=20, verbose_name='类别1'),
        ),
        migrations.AlterField(
            model_name='fpd_ratio',
            name='type_name',
            field=models.CharField(max_length=20, verbose_name='类别2'),
        ),
        migrations.AlterField(
            model_name='fpd_ratio',
            name='type_value',
            field=models.CharField(max_length=20, verbose_name='类别3'),
        ),
        migrations.AlterField(
            model_name='fpd_ratio',
            name='zc_nums',
            field=models.IntegerField(verbose_name='量'),
        ),
        migrations.AlterField(
            model_name='pass_ratio',
            name='apply_dt',
            field=models.CharField(max_length=20, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='pass_ratio',
            name='ins_score',
            field=models.CharField(max_length=20, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='pass_ratio',
            name='loan_nums',
            field=models.IntegerField(verbose_name='量'),
        ),
        migrations.AlterField(
            model_name='pass_ratio',
            name='pass_ratio',
            field=models.FloatField(null=True, verbose_name='率'),
        ),
        migrations.AlterField(
            model_name='pass_ratio',
            name='prod_line',
            field=models.CharField(max_length=20, verbose_name='类别1'),
        ),
        migrations.AlterField(
            model_name='pass_ratio',
            name='type_name',
            field=models.CharField(max_length=20, verbose_name='类别2'),
        ),
        migrations.AlterField(
            model_name='pass_ratio',
            name='type_value',
            field=models.CharField(max_length=20, verbose_name='类别3'),
        ),
        migrations.AlterField(
            model_name='score_propor',
            name='apply_dt',
            field=models.CharField(max_length=20, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='score_propor',
            name='ins_score',
            field=models.CharField(max_length=20, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='score_propor',
            name='prod_line',
            field=models.CharField(max_length=20, verbose_name='类别1'),
        ),
        migrations.AlterField(
            model_name='score_propor',
            name='type_name',
            field=models.CharField(max_length=20, verbose_name='类别2'),
        ),
        migrations.AlterField(
            model_name='score_propor',
            name='type_value',
            field=models.CharField(max_length=20, verbose_name='类别3'),
        ),
    ]
